infra/main.bicep, infra/main.json
Removed a param that want unnecessary
=> Removing dead param

src/backend/requirements.txt
This fixes the Linux tool use issue.
=> bug fix from sk upgrade

.flake8, src/backend/api/api_routes.py, src/backend/common/config/config.py, src/backend/common/database/database_base.py, src/backend/sql_agents/agents/agent_base.py, src/backend/sql_agents/convert_script.py, src/backend/sql_agents/helpers/agents_manager.py, src/backend/sql_agents/helpers/comms_manager.py, src/backend/sql_agents/process_batch.py
This pull request includes a change to the `src/backend/api/api_routes.py` file to clean up unused imports and improve code readability.
Code cleanup:
* Removed the unnecessary import of `process_batch_async` from `sql_agents_start`.
=> fix: removed duplicate import

.github/workflows/deploy.yml
This pull request updates the GitHub Actions workflow configuration to include a scheduled deployment. The most important change is the addition of a cron schedule to the `.github/workflows/deploy.yml` file.
Workflow configuration update:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R7-R8): Added a `schedule` trigger to run the deployment workflow at 5:00 AM and 5:00 PM GMT daily.
=> feat: scheduled one click deployment

infra/deploy_ai_foundry.bicep, infra/main.bicep, infra/main.json
This is a fix for errors users were having regarding the length of strings in the `Prefix` parameter.
- [x ] No
* ...
=>  `fix`: A bug fix for prefix string too long error

docs/DeploymentGuide.md
the link to the azureaccountsetup.md had an extra doc/
* ...
* ...
=> docs: Update DeploymentGuide.md

src/backend/requirements.txt
This pull request updates the `requirements.txt` file in the `src/backend` directory to include a new dependency for Azure AI Projects.
Dependency updates:
* [`src/backend/requirements.txt`](diffhunk://#diff-2a49eec19e44d96063fac307341e1bbc481f5eb25d41ba226e120cf0e94f690eR46): Added `azure-ai-projects==1.0.0b9` to the list of dependencies. This introduces the Azure AI Projects library, likely for use in AI-related features.## Purpose
* ...
* ...
=> fix: azure-ai-projects version change

src/backend/requirements.txt
* 
This pull request includes a small change to the `src/backend/requirements.txt` file. It removes a duplicate entry for `opentelemetry-exporter-otlp-proto-grpc` to clean up the dependencies.
* ...
=> fix: removed the duplicate package from requirements.txt

.github/workflows/azure-dev-validation.yml
* This pull request updates the environment configuration in the Azure DevOps validation workflow to ensure it aligns with the production environment.
* [`.github/workflows/azure-dev-validation.yml`](diffhunk://#diff-1dcfea15147980582b28c1b2c1b66b9841f315f12f68b855d8bc72f08aaa09d1L14-R14): Changed the `environment` from `dev` to `production` in the `template_validation_job` to reflect the correct deployment target.
* ...
=> ci: Environment configuration in the Azure DevOps validation workflow

infra/main.bicepparam
* ...
This pull request makes a small adjustment to the `infra/main.bicepparam` file, reducing the default value for the `capacity` parameter from 200 to 50. This change impacts the model capacity configuration for the Azure environment.
* ...
=> chore: updating the model capacity

docs/CustomizingAzdParameters.md, docs/DeploymentGuide.md, src/backend/api/api_routes.py
This pull request updates documentation to reflect changes in default parameter values and introduces new configuration options for Azure deployments. The most important changes include modifying default values for existing parameters, adding new parameters, and improving descriptions for deployment settings.
* [`docs/CustomizingAzdParameters.md`](diffhunk://#diff-6eec6ba43f4d3beb5835ad60e22b6974f1224c7b5ff024f690cd9549e8b4aec7L12-R13): Changed the default value of `AZURE_LOCATION` from `japaneast` to `eastus2`.
* [`docs/DeploymentGuide.md`](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9dafb6a4185d382bba81c4093aaaded7cL40-R50): Updated the default value for **Resource Prefix** to `azdtemp` and **Capacity** to `200`.
* [`docs/CustomizingAzdParameters.md`](diffhunk://#diff-6eec6ba43f4d3be …
=> docs: missing parameter added

infra/main.bicep
* This pull request introduces enhancements to the handling of Log Analytics workspaces in the `infra/main.bicep` file. The changes improve support for using an existing Log Analytics workspace by dynamically extracting its details and ensuring compatibility with both new and existing workspaces.
* **Dynamic extraction of existing workspace details**: Introduced logic to extract the subscription, resource group, and workspace name from the `existingLogAnalyticsWorkspaceId` parameter when an existing workspace is used. This is implemented using conditional expressions and the `split` function.
* **Support for existing Log Analytics workspace resources**: Added a new `resource` block to reference an existing Log Analytics workspace if specified, using the extracted details.
* **Unified …
=> fix: EXP Changes for log analytics workspace

docs/re-use-log-analytics.md
=> docs: Update links for re-use-log-analytics.md file

.github/workflows/azure-dev-validation.yml, scripts/checkquota.sh
* This pull request includes updates to improve compatibility with newer versions of tools and align with updated naming conventions. The most important changes are:
* Updated the Azure template validation action to use the latest version (`microsoft/template-validation-action@Latest`) in the `.github/workflows/azure-dev-validation.yml` file. This ensures the workflow uses the most up-to-date features and fixes.
* Updated the model name from `OpenAI.GlobalStandard.gpt4.1` to `OpenAI.GlobalStandard.gpt-4o` in the `scripts/checkquota.sh` file to align with the latest naming conventions for OpenAI models.
* ...
=> fix: Fix the Azd Template and Deploy pipeline issue

azure.yaml, docs/DeploymentGuide.md
This pull request includes updates to ensure compatibility with the latest version of the Azure Developer CLI (`azd`) and improves documentation clarity regarding version requirements.
* ...
* ...
=> docs: Added required azd version in azure.yml file and updated DeploymentGuide.md file

azure.yaml
This pull request includes a small change to the `azure.yaml` file. The change updates the required version of `azd` from `>=1.17.1` to `>1.17.1` to refine the version compatibility.
##** Purpose
* ...
* ...
=> docs: update azure.yml file with reuiredVersions

.github/workflows/telemetry-template-check.yml, azure.yaml
This pull request updates the GitHub Actions workflow to use the latest version of the `actions/checkout` action.
* [`.github/workflows/telemetry-template-check.yml`](diffhunk://#diff-4a309dbc21fc716da022fdb05209b134bf34b44aa5ce39f4e4125a06c5b0f51cL17-R17): Updated the `uses` directive in the `Checkout code` step to use `actions/checkout@v4` instead of `actions/checkout@v3`.
* ...
=> ci: Changed the Checkout version in telemetry-template-check.yml

src/backend/app.py, src/backend/common/services/batch_service.py, src/backend/sql_agents/agent_manager.py, src/backend/sql_agents/convert_script.py, src/backend/sql_agents/process_batch.py
This pull request introduces significant improvements to the backend application by integrating global SQL agent management and enhancing error handling and resource cleanup processes. Key changes include the addition of a global agent manager, modifications to the application lifespan for initializing and cleaning up agents, and updates to batch processing logic to utilize the global agent instance.
- **Global SQL agent management**:
- Added `src/backend/sql_agents/agent_manager.py` to manage a global SQL agents instance, including methods to set, get, update, and clear the instance. This avoids circular imports and simplifies agent lifecycle management.
- **Application lifespan management**:
- Updated `src/backend/app.py` to include an `asynccontextmanager`-based lifespan function for …
=> feat: Centralized agents Management

docs/CustomizingAzdParameters.md, docs/DeploymentGuide.md
Updated documentation to:
- Replace hardcoded AZURE_LOCATION value ("eastus2") with "User selects during deployment" to indicate user selection at deploy time.
- Adjust default AZURE_ENV_MODEL_CAPACITY from 200 to 150 for improved quota alignment.
These changes make the documentation more flexible and aligned with current deployment practices.
**Rewrote the environment configuration section in DeploymentGuide.md for better clarity and step-by-step guidance.**
Added clearer instructions for creating the .env file, retrieving values from the Azure Portal, and using the Azure CLI.
* ...
=> docs: make AZURE_LOCATION user-configurable in documentation

.github/workflows/azure-dev-validation.yml, infra/modules/cosmosDb.bicep
This pull request makes a minor update to the `.github/workflows/azure-dev-validation.yml` workflow configuration, enabling the `workflow_dispatch` trigger so the workflow can be run manually from the GitHub Actions UI.
* ...
=> refactor: Update template validation yaml
