microsoft/Modernize-your-code-solution-accelerator

.github/workflows/build-docker-images.yml, .github/workflows/build-docker.yml
This pull request introduces new workflows for building and optionally pushing Docker images. The changes are focused on setting up reusable and specific workflows for different branches and events.
* [`.github/workflows/build-docker-images.yml`](diffhunk://#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR1-R43): Added a new workflow to build Docker images for different branches (`main`, `dev`, `demo`, `hotfix`) and events (push, pull request, merge group, workflow dispatch). This workflow uses a matrix strategy to handle multiple applications (`cmsabackend`, `cmsafrontend`).
* [`.github/workflows/build-docker.yml`](diffhunk://#diff-1d203d2dfb96ccf94b5e0961c7954e3bde73b4539ade27ccc301613e368b944fR1-R78): Added a reusable workflow for Docker build and push operations. …
=> ci: build docker image and push to container registry

.github/workflows/build-docker-images.yml, .github/workflows/build-docker.yml
This pull request includes updates to the GitHub Actions workflows to use `github.ref_name` instead of `github.base_ref` for determining branch conditions. This change ensures more accurate branch detection in various workflow steps.
Changes to GitHub Actions workflows:
* [`.github/workflows/build-docker-images.yml`](diffhunk://#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eL42-R42): Updated the `push` condition to use `github.ref_name` instead of `github.base_ref`.
* [`.github/workflows/build-docker.yml`](diffhunk://#diff-1d203d2dfb96ccf94b5e0961c7954e3bde73b4539ade27ccc301613e368b944fL54-L63): Modified the branch checks in the `determine_tag` step to use `github.ref_name` instead of `github.base_ref`. Removed the `dependabotchanges` branch condition.
=> fix: skip docker login on push

src/frontend/src/pages/modernizationPage.tsx
This pull request enhances the functionality of the `ModernizationPage` component in `modernizationPage.tsx` by improving file processing and summary status handling. The changes introduce a new utility function for updating summary status, refactor existing file state updates for better clarity, and ensure consistent handling of completed file batches.
* Added a new `updateSummaryStatus` function to centralize logic for updating the batch summary, checking file statuses, and enabling/disabling the ZIP button based on the presence of usable files.
* Updated the `useEffect` hooks to ensure the summary status is refreshed whenever all files reach a terminal state or when all non-summary files are completed. This ensures a single source of truth for summary updates.
* Removed redundant logic …
=> fix: modernization page summary label issue

infra/deploy_keyvault.bicep, infra/main.json
This pull request updates the configuration for Key Vault resources in the infrastructure files, removing certain settings related to soft delete and purge protection, and regenerating template hashes to reflect these changes.
* [`infra/deploy_keyvault.bicep`](diffhunk://#diff-82312b3acfa82a4f0980d7e0592f22b8db36f98965a61c340510f972ad7306faL38-L40): Removed `enableSoftDelete` and `enablePurgeProtection` properties from the Key Vault configuration. These settings are no longer explicitly defined.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L507-L509): Updated the Key Vault configuration to remove `enableSoftDelete` and `enablePurgeProtection` properties, aligning with the changes in the Bicep file.
* …
=> feat: disable purge protection of key vault

src/frontend/src/components/uploadButton.tsx, src/frontend/src/pages/batchView.tsx
This pull request updates the wording in confirmation dialogs across the application to improve user clarity and consistency. Specifically, the "Cancel" button text has been changed from "Stay here" to "Continue" in two places.
Dialog text updates:
* [`src/frontend/src/components/uploadButton.tsx`](diffhunk://#diff-6ee566319b7b57a4566f4825bde5bc576033af50d62ccdb85f89e23e43d9850fL369-R369): Updated the `cancelText` in the file upload cancellation dialog from "Stay here" to "Continue" to align with the updated user experience.
* [`src/frontend/src/pages/batchView.tsx`](diffhunk://#diff-cdeb9de1e80ac6996465fb16cd07e14aa8d7467e05252cbcae76fe15b40efb7bL670-R670): Updated the `cancelText` in the leave confirmation dialog from "Stay here" to "Continue" for consistency.
=> fix: bring consistency for "cancel" behavior from home screen

.github/workflows/deploy.yml
This pull request updates the deployment workflow in `.github/workflows/deploy.yml` to align parameter naming conventions with Azure standards.
* **Deployment workflow parameter update**:
- Updated the `az deployment group create` command to rename the `ResourcePrefix` parameter to `Prefix` and `AiLocation` to `AzureAiServiceLocation` for consistency with Azure naming conventions. (`.github/workflows/deploy.yml`, [.github/workflows/deploy.ymlL61-R61](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L61-R61))
=> feat: updated one click deployment github action parameters

infra/main.bicep, infra/main.json
This pull request removes the `apiProperties` configuration, specifically the `statisticsEnabled` property, from the `Microsoft.CognitiveServices/accounts` resource in both the Bicep and JSON infrastructure templates. The change simplifies the resource definition by eliminating unused or unnecessary properties.
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L78-L80): Removed the `apiProperties` block, which previously disabled statistics (`statisticsEnabled: false`) for the `Microsoft.CognitiveServices/accounts` resource.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L103-L105): Removed the equivalent `apiProperties` block from the JSON template, aligning it with the changes …
=> fix: removed apiProperties.statisticsEnabled property from code

.dockerignore
- This PR adds a ".dockerignore" file to prevent unnecessary files and directories (such as virtual environments, build artifacts, logs, node_modules, and IDE configs) from being sent to the Docker daemon during image builds.
- Confirm .dockerignore is present at root directory.
- Ensure expected files (e.g. .git, node_modules, __pycache__, etc.) are excluded from build context.
- Run a Docker build and verify only necessary files are included.
=> build: Add .dockerignore to optimize Docker build context

.github/workflows/deploy.yml
This pull request enhances the deployment workflow by introducing dynamic resource handling, including the generation of unique solution prefixes, integration of OpenAI resources, and improved resource cleanup processes. Below is a breakdown of the most important changes:
* Added a step to generate a unique solution prefix using a timestamp, which is dynamically assigned to the `Prefix` parameter during deployment. (`.github/workflows/deploy.yml`, [.github/workflows/deploy.ymlR54-R73](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R54-R73))
* Updated the resource-fetching step to include the retrieval of OpenAI resources from the resource group, ensuring their availability for subsequent operations. (`.github/workflows/deploy.yml`, …
=> fix: one click deployment github action issue

infra/deploy_ai_foundry.bicep, infra/main.bicep, infra/main.json
This pull request focuses on standardizing naming conventions and improving parameter handling in the Bicep infrastructure files. The most significant changes involve replacing inconsistent variable names, refining resource prefixes, and ensuring that parameters conform to updated naming and length constraints.
* Updated variable names to replace `prefixCleaned` with `ResourcePrefix` across multiple resources, ensuring consistency in naming conventions. (`infra/main.bicep`: [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L52-R52) [[2]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L114-R106) [[3]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L128-R118) …
=> refactor: standardize naming conventions and parameter handling in Bicep templates1

.github/dependabot.yml, .github/workflows/scheduled-Dependabot-PRs-Auto-Merge.yml
* Introduced a scheduled GitHub Actions workflow to auto-approve and auto-merge Dependabot PRs targeting the dependabotchanges branch.
* Also optimized the dependabot.yml configuration to group dependency updates by ecosystem and path, significantly reducing PR noise.
* Enhanced rebase logic to handle merge conflicts using --strategy-option=theirs.
* Implemented multi-strategy auto-merge (merge, squash, rebase) with fallback handling.
* Improved overall script reliability and compatibility with repo-level merge restrictions.
* ...
=> chore: Updated Dependabot config to group PRs and added workflow for scheduled auto-merge

docs/CustomizingAzdParameters.md, docs/DeploymentGuide.md, infra/deploy_ai_foundry.bicep, infra/main.bicep, infra/main.bicepparam
* User can now reuse existing log analytics workspace instead of creating new one
* ...
=> feat: Implemented Reusing Log analytics workspace

docs/DeploymentGuide.md
This pull request updates the deployment guide to clarify region-specific constraints for deploying the application. The most important change is the addition of a detailed list of supported Azure regions, along with a warning to ensure correct region selection during deployment.
* [`docs/DeploymentGuide.md`](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9dafb6a4185d382bba81c4093aaaded7cL13-R26): Added a section titled "Region-Specific Deployment Constraints" with a warning and a detailed list of supported Azure regions for deploying the application. This aims to prevent deployment failures due to unsupported regions.## Purpose
* ...
* ...
=> fix: deployment region readme changes

docs/CustomizingAzdParameters.md, infra/main.bicep, infra/main.bicepparam
This pull request introduces several enhancements and updates across multiple areas, including development environment configuration, test automation, documentation, and infrastructure deployment. The most significant changes involve adding new Azure CLI features to the dev container, creating a new GitHub Actions workflow for test automation, and updating infrastructure templates to include Application Insights integration.
* Added the Azure CLI feature with Bicep support to the dev container configuration (`.devcontainer/devcontainer.json`). This includes setting the `installBicep` option to `true` and specifying the latest versions for Azure CLI and Bicep.
* Updated the VS Code extensions list to include `ms-azuretools.vscode-azcli` for enhanced Azure CLI support.
* Introduced a new …
=> feat: Standardize Bicep Parameters for Code Modernization

docs/CustomizingAzdParameters.md, infra/deploy_ai_foundry.bicep
This pull request introduces improvements to the handling of existing Log Analytics Workspace IDs in both documentation and infrastructure code. The changes ensure consistency and correctness when specifying the full resource ID format and enhance the deployment logic to accommodate subscriptions explicitly.
* [`docs/CustomizingAzdParameters.md`](diffhunk://#diff-6eec6ba43f4d3beb5835ad60e22b6974f1224c7b5ff024f690cd9549e8b4aec7L28-R28): Updated the example for setting the `AZURE_ENV_LOG_ANALYTICS_WORKSPACE_ID` to use the full resource ID format, including subscription, resource group, and workspace name.
* [`infra/deploy_ai_foundry.bicep`](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626R18): Added logic to extract the subscription ID …
=> fix: To reuse Log Analytics across subscriptions

scripts/validate_model_deployment_quota.ps1, scripts/validate_model_deployment_quota.sh, scripts/validate_model_quota.ps1, scripts/validate_model_quota.sh
* ...
This pull request introduces several enhancements to scripts responsible for validating model deployment quotas in Azure. The changes improve error handling, streamline parameter validation, and add checks for existing services and deployments to optimize quota validation. Below is a summary of the most important changes grouped by theme:
* Enhanced validation logic in `scripts/validate_model_deployment_quota.ps1` and `scripts/validate_model_quota.ps1` to check for missing or invalid parameters and provide clearer error messages. [[1]](diffhunk://#diff-f436047f2fd4d73338a85fbba88d0d1d91e5f485b6e8d3b97c8cdabff0c1e4d2L7-L17) [[2]](diffhunk://#diff-be9d5b27ecd8e64d43cdb15bfc501e6a9a00c4a91309c457a6167a1746439540L8-R8)
* Updated `scripts/validate_model_deployment_quota.sh` and …
=> fix: prefer user region then all other region

azure.yaml, scripts/validate_model_deployment_quota.ps1, scripts/validate_model_deployment_quota.sh, scripts/validate_model_quota.ps1, scripts/validate_model_quota.sh
* ...
This pull request introduces several changes to improve the validation and deployment of AI models in Azure services. Key updates include enhanced parameter validation, better handling of missing deployments, and improved quota checks across regions. The changes span multiple scripts and configuration files, ensuring more robust and user-friendly workflows.
* Updated parameter names in `scripts/validate_model_deployment_quota.sh` and `scripts/validate_model_deployment_quota.ps1` for consistency (`--subscription` → `--SubscriptionId`, `--location` → `--Location`, `--models-parameter` → `--ModelsParameter`) and improved error messages for missing or unknown parameters. [[1]](diffhunk://#diff-1485c0125e236c5138a63293d8d71a2b7b252bef8cf9feacc805090b08e7c7c9L9-R81) …
=> feat: implement interactive quota check script with user inputs

scripts/validate_model_quota.ps1, scripts/validate_model_quota.sh
* ...
This pull request introduces several enhancements and fixes across deployment scripts, infrastructure configuration, and documentation. The key changes include improving validation scripts for quota checks, updating default parameters for Azure regions and capacities, and enhancing error handling and output formatting.
* Enhanced `validate_model_deployment_quota.ps1` and `validate_model_deployment_quota.sh` scripts to include discovery of AI Foundry names and validation of existing model deployments before proceeding with quota checks. Improved error handling and output for missing parameters and quota validation results. [[1]](diffhunk://#diff-f436047f2fd4d73338a85fbba88d0d1d91e5f485b6e8d3b97c8cdabff0c1e4d2L7-R75) [[2]](diffhunk://#diff-f436047f2fd4d73338a85fbba88d0d1d91e5f485b6e8d3 …
=> fix: quota validation script update

tests/e2e-test/pytest.ini, tests/e2e-test/readme.MD, tests/e2e-test/requirements.txt, tests/e2e-test/tests/conftest.py, tests/e2e-test/tests/test_codegen_gp_tc.py
* https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/19053/
* ...
=> test: Implemented Log execution time per prompt in Report

.github/workflows/deploy.yml, .github/workflows/test-automation.yml, infra/deploy_keyvault.bicep, infra/main.bicep, infra/main.json
* Significant updates to the deployment and test automation workflows, focusing on enhancing flexibility, adding cleanup processes, and improving parameterization.
* ...
=> test: Integration of deploy & test automation

src/backend/api/api_routes.py
* ...
This pull request introduces logging, telemetry, and event tracking enhancements to the `src/backend/api/api_routes.py` file. Key changes include the integration of Azure Application Insights, the addition of OpenTelemetry exception tracing, and event tracking for key API operations.
* Integrated Azure Application Insights for telemetry by checking for the `APPLICATIONINSIGHTS_CONNECTION_STRING` environment variable and configuring it if present. Suppressed verbose logs from specific Azure and OpenTelemetry components. [[1]](diffhunk://#diff-f63315206e268b715ccf12ba9a1d7017d947b59e01745d78ab42d66396c6c30eR3-R18) [[2]](diffhunk://#diff-f63315206e268b715ccf12ba9a1d7017d947b59e01745d78ab42d66396c6c30eR34-R75)
* Added a utility function `record_exception_to_trace` to log exceptions to …
=> chore: re-enable OpenTelemetry Azure Monitor

infra/modules/network.bicep, infra/modules/network/bastionHost.bicep, infra/modules/network/main.bicep, infra/samples/network-subnet-design.bicep
* This pull request refactors and enhances the Azure Bastion Host module by introducing a more structured and reusable subnet configuration, integrating Network Security Groups (NSGs) for improved security, and updating dependent modules to align with these changes. The most significant updates include replacing the flat `subnetAddressPrefixes` parameter with a new `subnet` object, adding NSG definitions, and updating module dependencies and outputs accordingly.
* Replaced `subnetAddressPrefixes` with a new `subnet` object in `bastionHostConfigurationType`, enabling more detailed configuration of subnets, including name, address prefixes, and associated NSG details. (`infra/modules/network/bastionHost.bicep`, [[1]](diffhunk://#diff-586521915e365afbe312e7c1133c3b81cb42b3cfbfc8aea4ab59231df1 …
=> fix: Create NSG for bastion and Pep subnet to avoid auto creation NSG by policy

infra/main.bicep, infra/main.json, infra/main.parameters.json, infra/modules/ai-foundry/dependencies.bicep, infra/modules/ai-foundry/keyVaultExport.bicep, infra/modules/ai-foundry/main.bicep, infra/modules/ai-foundry/project.bicep, infra/samples/network_subnet_design.md
This pull request introduces several enhancements and updates to the `infra` Bicep files, primarily focusing on support for existing AI projects, improved resource configurations, and the addition of a new module for Key Vault secret management. Below is a summary of the most important changes grouped by theme.
* Added a new parameter `azureExistingAIProjectResourceId` to allow reuse of an existing AI project resource ID in `infra/main.bicep` and `infra/main.parameters.json`. [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4R99-R101) [[2]](diffhunk://#diff-834bc11e3cb55730076a7d70767b75f794dc9a37305f27d99926e0fd24363c13R29-R31)
* Updated the `aiServices` module to include configurations for reusing existing AI project resources, such as …
=> chore: Reuse AI Foundry Project

src/backend/common/database/cosmosdb.py, src/tests/backend/common/database/cosmosdb_test.py
This pull request refactors the Cosmos DB initialization logic to simplify container access by removing the logic for creating containers if they do not exist. Instead, the code now directly fetches existing containers. Corresponding unit tests have been updated to reflect this new approach.
**Cosmos DB Initialization Refactor:**
* The `initialize_cosmos` method in `cosmosdb.py` now uses a new `_get_container` helper that only fetches containers with `get_container_client` instead of attempting to create them if they don't exist. This removes the need for handling container creation and related exceptions.
**Test Updates:**
* All unit tests in `cosmosdb_test.py` have been updated to mock and assert calls to `get_container_client` instead of `create_container`, reflecting the new logic …
=> fix: removed the container creation from code to avoid permission issue

src/frontend/frontend_server.py
This pull request introduces important security enhancements to the FastAPI frontend server. The changes focus on preventing unauthorized access to sensitive files, mitigating directory traversal attacks, and adding security headers to HTTP responses.
**Security improvements for static file serving:**
* Added path resolution and validation logic in the `serve_app` endpoint to prevent directory traversal and ensure only files within the build directory are served.
* Implemented checks to block access to dotfiles, forbidden file extensions (e.g., `.env`, `.py`, `.key`), and forbidden filenames (e.g., `Dockerfile`, `.secrets`). Suspicious requests now return a 404 error. [[1]](diffhunk://#diff-163320c83714f7af2dd9c8332e03a952c7ec5418861fe4202b3d1fe471de49a3R27-R50) …
=> fix: SFI issue fix

src/frontend/src/components/uploadButton.tsx
https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/22335/
* 
This pull request improves the file upload experience in the `FileUploadZone` component by adding stricter validation for uploaded files and providing clear feedback to users when files are rejected. The changes ensure that only `.sql` files are accepted and that users are informed of any issues with their uploads, such as invalid file type or exceeding the size limit.
**File validation and error handling improvements:**
* Added a manual check to ensure only files with a `.sql` extension are accepted, regardless of MIME type, and constructed detailed error messages for invalid files and files exceeding the size limit. These errors are displayed to the user.
* Introduced the `fileRejectionErrors` state to track and …
=> feat:  Meaningful error notification if file upload fails due to uploading invalid file

infra/main.bicep
This pull request makes a small but useful improvement to the resource group tagging logic in `infra/main.bicep`. The change adds a new `CreatedBy` tag that automatically sets the creator's username based on the deployment principal.
* Tagging enhancement: The `CreatedBy` tag is now added to the resource group tags, using the username portion of the `userPrincipalName` from the deployer context.
* ...
* ...
=> chore: Add user name as CreatedBy tag while deployment
